package com.irsyad.pulse.engine.model.enums;

/**
 * Types of insights generated by the Pulse Engine.
 */
public enum InsightType {

    HIGH_AMOUNT,
    CUSTOMER_FIRST_PURCHASE,
    PAYMENT_RETRY,
    HIGH_FRAUD_RISK,
    VELOCITY_ANOMALY,
    PAYMENT_METHOD_RISK,
    CUSTOMER_BEHAVIOR
}