# =============================================================================
# Pulse Engine — Production Profile
# =============================================================================
%prod.quarkus.http.port=8084
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/pulse
%prod.kafka.bootstrap.servers=kafka:9092
%prod.quarkus.log.console.level=INFO
%prod.quarkus.log.console.format=%d{HH:mm:ss} %-5p [%X{correlation-id}] [%X{trace-id}] %c - %m%n
